### ISSUE TITLE
ModuleNotFoundError: No module named 'classification'

### ISSUE THREAD

**Issue by yeshwanth95** [TLSeparation/source#3]
I'm trying to install the TLSeparation library in a conda (4.7.12) environment.
I'm using pip to install the library within the conda environment having python 3.6.
Although the installation occurs, when I try to import the library from within a python script, I get the following error:

> Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tlseparation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vr-lab/anaconda3/envs/tlsep_env/lib/python3.6/site-packages/tlseparation/__init__.py", line 30, in <module>
    import classification
ModuleNotFoundError: No module named 'classification'

I'm using Ubuntu 16.04 LTS. 
@mattbv @philwilkes  Kindly provide me assistance in resolving this issue.

**Comment by tpet93** [comment]
I believe this is because TLSeperation is python 2.
Either run in python 2 or change the imports to
`from . import classification`
you will also need to change several other parts in the code to run in python 3

**Comment by orchid00** [comment]
hi, same issue.
just installed 
`pip install tlseparation`
run 
```
import tlseparation
ModuleNotFoundError: No module named 'classification'
```
run 
`pip install classification`
```
import tlseparation
ModuleNotFoundError: No module named 'utility'
```

run 
`pip install utility`

and again
```
import tlseparation
ModuleNotFoundError: No module named 'utility'
```

using Python 3.6.9 on Ubuntu 18.04
ping @mattbv

**Comment by philwilkes** [comment]
Owing to the way modules are referenced within TLSeparation you will need to run in a Python 2 environment.

I have a conda environment specifically for running TLSeparation. Something like:

`conda create --name tlseparation python=2` as well as dependencies (see [requirements.txt](https://github.com/TLSeparation/source/blob/master/requirements.txt)) 

or you could then do a `pip install tlseparation` inside the new environment (although this is not the *best* way to install dependencies).

**Comment by anapatriciarb** [comment]
Thanks Phil. I actually tried today but with Python 2.7 and it did not work. I'll give it a go with Python 2.0.
